### ISSUE TITLE
Hangs Messages on my device, 13.1

### ISSUE THREAD

**Issue by NSExceptional** [jacobcxdev/iDunnoU#2]
I will try to debug this myself later

**Comment by jacobcxdev** [comment]
Thanks for the report. Have you got any other Messages tweaks installed?

~~I’ll need FLEX v4 to debug this (pls it looks awesome) /s~~.

**Comment by jacobcxdev** [comment]
Hi, did you manage to resolve this? @NSExceptional

**Comment by NSExceptional** [comment]
I have not, I've been busy with FLEX

**Comment by jacobcxdev** [comment]
Okay, I apologise that you’re facing issues. I have an update in the works (see the dev branch), and perhaps that will work for you.

**Comment by jacobcxdev** [comment]
Fixed in 36723905ca4675079381865ca5f96359b75dee38.
